Display detailed error messages from the stack (#99)
torch_onnx.errors.OnnxConversionError: Failed to convert the exported
program to an ONNX model. This is step 2/2 of exporting the model to
ONNX. Next steps:
- If there is a missing ONNX function, implement it and register it to
the registry.
- If there is an internal error during ONNX conversion, debug the error
and summit a PR to PyTorch.
- Save the ExportedProgram as a pt2 file and create an error report with
`export(error_report=True)`. Create an issue in the PyTorch GitHub
repository against the *onnx* component. Attach the pt2 model and the
error report.

## Exception summary

<class 'torch_onnx.errors.DispatchError'>: No ONNX function found for
<OpOverload(op='aten.index', overload='Tensor')>. Failure message: No
decompositions registered for the complex-valued input
⬆️
<class 'torch_onnx.errors.OnnxConversionError'>: Error when translating
node %index : [num_users=1] =
call_function[target=torch.ops.aten.index.Tensor](args = (%arg0_1,
[%lift_fresh_copy, %lift_fresh_copy_1, %arg7_1]), kwargs = {}). See the
stack trace for more information.

(Refer to the full stack trace above for more information.)